#!/usr/bin/env sh

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export PATH=$HOME/.local/bin:$PATH
export VISUAL=/usr/bin/nvim
export EDITOR=$VISUAL
export TERMINAL=/usr/bin/gnome-terminal
export PAGER=/usr/bin/less
export TERM=xterm-256color

export GTK2_RC_FILES=/usr/share/themes/Arc/gtk-2.0/gtkrc

xautolock -locker 'dm-tool lock' &
