alias t '$TERMINAL'
alias e '$VISUAL'

alias paci 'sudo pacman -S'
alias pacd 'sudo pacman -Rns'
alias pacu 'sudo pacman -Syu'
alias pacr 'sudo pacman -Sy'
alias pacs 'pacman -Ss'
alias pacq 'pacman -Qs'
alias pacorphans 'pacman -Qqdt'
